name: Lua formatting & lint

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    name: stylua + selene
    runs-on: ubuntu-slim
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Install stylua
        run: |
          curl -LO https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip
          unzip stylua-linux-x86_64.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/

      - name: Install selene
        run: |
          curl -LO https://github.com/Kampfkarren/selene/releases/download/0.27.1/selene-0.27.1-linux.zip
          unzip selene-0.27.1-linux.zip
          chmod +x selene
          sudo mv selene /usr/local/bin/

      - name: Run stylua formatting check
        run: stylua --config stylua.toml --check .config/nvim

      - name: Run selene lint
        run: selene --config selene.toml .config/nvim
